channels:
  - conda-forge
  - defaults
  - litex-hub
dependencies:
  - git=2.46.0
  - wget=1.21.4
  - flex=2.6.4
  - bison=3.8.2
  - gperf=3.1
  - python=3.10
  - cmake=3.30.1
  - ninja=1.12.1
  - ccache=4.10.1
  - libffi=3.4.2
  - openssl=3.3.1
  - dfu-util
  - libusb=1.0.27
